<%@ Page Language="C#" EnableEventValidation="false" AutoEventWireup="true" CodeFile="RelatorioDistribuicaoVirada.aspx.cs" Inherits="_Default"%><%@ Register Src="inc/BarraIdentificacao.ascx" TagName="Barra" TagPrefix="ucBarra"%><!--#include file="inc/FWMNUSUB.aspx"--><!-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::Empresa           : Fourway InformáticaSistema           : FWUNFArquivo           : RelatorioViradaTempo.aspx Criado em         : 09/05/2012Última Alteração  : Versão            : 1.00Descrição         : Módulo para Relatório Distribuição de Virada:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::--><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head id="Head" runat="server"><link rel="stylesheet" type="text/css" href="css/FW.css"/>	<title><% Response.Write(ConfigurationManager.AppSettings["Titulo"]); %></title></head><body id="bdyDST_VRD" runat="server" class="bg" style="margin-left:0;margin-right:0;margin-top:0;margin-bottom:0;width:780px"><form id="frmDST_VRD" runat="server"><asp:HiddenField ID="Origem" runat="server" /><asp:HiddenField ID="rowId" runat="server" /><asp:HiddenField ID="hid_epf_id" runat="server" /><script type="text/javascript" language="javascript" src="scr/FWGNR.js"></script><script type="text/javascript" language="javascript" src="scr/FWMNU.js"></script><ucBarra:Barra ID="ucBarra" runat="server"></ucBarra:Barra><div style="left:5px"><div runat="server" id="dvFiltro" visible="true"><table style="width:780px" align="center" border="0" cellspacing="4" cellpadding="0">	<tr>		<td colspan="2" class="font_titulo_grd" style="width:1024px">			Pesquisar Distribuição de Virada		</td>	</tr>	<tr>		<td colspan="2">&nbsp;</td>	</tr>	<tr>		<td colspan="2" class="font_body">Data Inicial</td>	</tr>	<tr>		<td colspan="2">			<asp:TextBox id="txt_dat_ini" runat="server" CssClass="text_box" maxlength="10" style="width:100px"></asp:TextBox>		</td>	</tr>	<tr>		<td colspan="2" class="font_body">Data Final</td>	</tr>	<tr>		<td colspan="2">			<asp:TextBox id="txt_dat_fim" runat="server" CssClass="text_box" maxlength="10" style="width:100px"></asp:TextBox>		</td>	</tr>	<tr>		<td colspan="2" class="font_body">Turno</td>	</tr>	<tr>		<td>
			<asp:DropDownList ID="cbo_tur" runat="server" CssClass="combo_box">
				<asp:ListItem value=""></asp:ListItem>
				<asp:ListItem value="TURNO 1" Text="TURNO 1 - 05:01 a 14:59"></asp:ListItem>
				<asp:ListItem value="TURNO 2" Text="TURNO 2 - 13:01 a 22:59"></asp:ListItem>
				<asp:ListItem value="TURNO 3" Text="TURNO 3 - 21:01 a 06:59"></asp:ListItem>
			</asp:DropDownList>
		</td>
	</tr>	<tr>		<td colspan="2" class="font_body">Agrupado</td>	</tr>	<tr>		<td>
			<asp:DropDownList ID="cbo_agu" runat="server" CssClass="combo_box">
				<asp:ListItem value="SIM" Text="SIM"></asp:ListItem>
				<asp:ListItem value="NÃO" Text="NÃO"></asp:ListItem>
			</asp:DropDownList>
		</td>
	</tr>	<tr>		<td colspan="2">&nbsp;</td>	</tr>	<tr>		<td colspan="2">			<asp:Button ID="btProcurar"   runat="server" CssClass="botao" Text="Listar" OnClick="btProcurar_Click" /> &nbsp;&nbsp;		</td>	</tr></table></div><div runat="server" id="dvDistribuicao" style="width:780px; border: 0px;" visible="false"><style>    .td_operador { background-color:Silver; font-weight:bold; font-family:Courier New; font-size:12px; }    .td_distribuicao { border-top: 1px solid white; border-bottom: 1px solid black; text-align:right; font-family:Courier New; font-size:12px; }    table tr.page-break{page-break-after:always}</style><table id="tDistribuicao" runat="server" style="border: 0px;"></table></div></div></form></body></html>